---
- name: Install ClickHouse
  hosts: clickhouse
  become: true
  tags:
    - clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  become: true
  tags:
    - vector
  roles:
    - vector

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  tags:
    - lighthouse
  roles:
    - lighthouse
